# ref: https://github.com/TESSEorg/ttg/blob/master/.github/workflows/cmake.yml
name: Linux/MacOS Build

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type : [ Release, Debug ]
        os : [ macos-latest, ubuntu-22.04 ]
        device : [host]
        include:
          - os: ubuntu-22.04
            cc: /usr/bin/gcc-12
            cxx: /usr/bin/g++-12
          - os: macos-latest
            cc: clang
            cxx: clang++

    name: "${{ matrix.os }}: ${{ matrix.cxx }} ${{ matrix.device }} ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}
    env:
      CXX : ${{ matrix.cxx }}
      DOXYGEN_VERSION : 1.9.2
      GH_MRA_TTG_TOKEN : ${{ secrets.GH_MRA_TTG_TOKEN }}
      CCACHE_DIR : ${{github.workspace}}/build/.ccache
      CCACHE_COMPRESS : true
      CCACHE_COMPRESSLEVEL : 6
      OMPI_MCA_btl_vader_single_copy_mechanism : none
      PARSEC_MCA_runtime_bind_threads : 0
      BUILD_CONFIG : >
        -G Ninja
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_PREFIX_PATH=/usr/local/opt/bison
        -DBUILD_SHARED_LIBS=OFF
        -DMPIEXEC_PREFLAGS='--bind-to;none;--allow-run-as-root'
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
        -DTTG_PARSEC_USE_BOOST_SERIALIZATION=OFF
        -DCMAKE_CXX_STANDARD=20
    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisite MacOS packages
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install ninja boost eigen open-mpi bison ccache
        echo "MPIEXEC=/opt/homebrew/bin/mpiexec" >> $GITHUB_ENV
    - name: Install prerequisites Ubuntu packages
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get -y install ninja-build g++-12 liblapack-dev libboost-dev libboost-serialization-dev libboost-random-dev libeigen3-dev openmpi-bin libopenmpi-dev libtbb-dev ccache flex bison cmake doxygen
        echo "MPIEXEC=/usr/bin/mpiexec" >> $GITHUB_ENV
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: |
        cmake -E make_directory ${{github.workspace}}/build
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
    - name: Setup ccache cache files
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/build/.ccache
        key: ${{ matrix.config.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ matrix.config.name }}-ccache-
    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_CONFIG || (cat CMakeFiles/CMakeOutput.log && cat CMakeFiles/CMakeError.log)
    - name: Build [host]
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: ccache -p && ccache -z && cmake --build . && ccache -s
    - name: Test Derivative [host]
      if: ${{ matrix.device == 'host' }}
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./src/mra-mad-deriv-host-parsec
    - name: Test PCR [host]
      if: ${{ matrix.device == 'host' }}
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./src/mra-pcr-host-parsec

    - name: Test Transition Matrices [host]
      if: ${{ matrix.device == 'host' }}
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./src/mra-trmatrixtest

